### ISSUE TITLE
我在28181服务器上获取流时客户端出现以下报错，您有遇到过着问题吗。

### ISSUE THREAD

**Issue by MacianYuan** [husanpao/gb28181_client_linux#1]
[2022-07-23 10:21:38.414] [info] unhandled sip evt type: 27
[2022-07-23 10:21:44.968] [info] got CALL_INVITE
[2022-07-23 10:21:44.968] **[error] eXosip_get_remote_sdp failed**

**Comment by husanpao** [comment]
exosip的版本呢？是使用的我提供的吗？你使用的系统版本呢？这个一般是包问题引起的，可以尝试手动编译一次高版本exosip。

**Comment by 00010010** [comment]
你好 我在编译exosip5.2.0版本的时候遇到了1楼同样的问题，我编译exosip4.1.0版本的时会报一下错，请问有什么解决思路吗？

```
sXtl_dtls.c:236:43:error:dereferencing pointer to incomplete type 'SSL' {aka 'struct ssl_st‘}
236 |     (reserved->socker_tab[pos].ssl_conn)->rbio = rbio;
```

**Comment by 00010010** [comment]
`eXtl_dtls.c:236:43:error:dereferencing pointer to incomplete type 'SSL' {aka 'struct ssl_st‘}
236 |     (reserved->socker_tab[pos].ssl_conn)->rbio = rbio;`

**Comment by WOODENb** [comment]
> [2022-07-23 10:21:38.414] [info] unhandled sip evt type: 27 [2022-07-23 10:21:44.968] [info] got CALL_INVITE [2022-07-23 10:21:44.968] **[error] eXosip_get_remote_sdp failed**

我也遇到了eXosip_get_remote_sdp failed，请教一下你是怎么解决的？

**Comment by WOODENb** [comment]
> 你好 我在编译exosip5.2.0版本的时候遇到了1楼同样的问题，我编译exosip4.1.0版本的时会报一下错，请问有什么解决思路吗？
> 
> ```
> sXtl_dtls.c:236:43:error:dereferencing pointer to incomplete type 'SSL' {aka 'struct ssl_st‘}
> 236 |     (reserved->socker_tab[pos].ssl_conn)->rbio = rbio;
> ```
我也遇到了eXosip_get_remote_sdp failed，请教一下你是怎么解决的？
